version: '3.9'

services:
    redis:
        container_name: storage
        image: redis:6.2.7-alpine
        restart: unless-stopped
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis-data:/data/
    website:
        container_name: url_shortener
        build: .
        restart: unless-stopped
        ports:
            - ${PORT}:2000
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  redis-data:
    driver: local
